INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Apple', 'Designer', '13', 43282, 13.000);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Dell', 'Process', '9', 95393, 9000.00);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Samsung', 'HD', '7', 30293, 6000.00);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Lenovo', 'Disk', '9', 84390, 8000.000);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Accer', 'Image', '10', 49434, 3800.00);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Cce', 'Image', '9', 98342, 4000.00);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Xiaomi', 'Process', '8', 98549, 8000.00);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook HP', 'Disk', '6', 98439, 2900.00);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Asus', 'Desiner', '7', 32894, 2700.00);
INSERT INTO TB_COMPUTERS (NAME, DESCRIPTION, MODEL, SERIE_NUMBER, PRICE) VALUES ('Notebook Positivo', 'HD', '7', 30943, 2300.00);

